exporter:
  # port：PowerStore exporter port number
  port: 9010
  # reqLimit：The number of times the PowerStore exporter makes requests to the PowerStore manager api at the same time
  reqLimit: 200
  # bulkDir：PowerStore exporter requests the data storage directory after the data obtained by the PowerStore manager bulk api
  bulkDir: ./bulk/
  # bulkCron：PowerStore exporter requests from PowerStore manager bulk API regularly
  bulkCron: "*/5 * * * *"
  https:
    # https.enable: enableDoes PowerStore exporter need to enable https access
    enable: false
    # https.crtPath & https.keyPath:The certificate path used by https of PowerStore exporter
    crtPath: ./https/https.crt
    keyPath: ./https/https.key
log:
  # type：PowerStore exporter log type, optionally logfmt or json
  type: logfmt
  # path: PowerStore exporter log output file
  path: ./powerstoreExporter.out.log
  # level: Minimum log level printed by PowerStore exporter
  level: info
storageList:
    # ip: The IP address of PowerStore manager API
  - ip: 10.0.0.1
    # user: Login users of PowerStore manager api
    user: your-first-powerstore-username
    # password：Password of the user logged in with PowerStore Manager API
    password: your-first-powerstore-password
    # apiVersion: It is recommended to use v1 for PowerStore OS versions below 3.6, and v3 for versions 3.6 and above
    apiVersion: v3
    # apiLimit：The maximum number of components output per output by PowerStore Manger API
    apiLimit: 5000
    # bulkCollector：Whether to enable PowerStore manager bulk api to collect data
    # This value must be set to true for PowerStore OS versions 4.1.0.0 and above. It must also be set to true if data retrieval times out due to a large number of volumes, file systems, or similar resources
    bulkCollector: false
  - ip: 10.0.0.2
    user: your-second-powerstore-username
    password: your-second-powerstore-password
    apiVersion: v3
    apiLimit: 5000
    bulkCollector: false